FROM python:3.8

WORKDIR scripts/

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY scripts/* ./

RUN chmod 777 run_provision.sh

CMD ["./run_provision.sh" ]