FROM python:3.8-alpine

#COPY requirements.txt /tmp/
#RUN pip install -r /tmp/requirements.txt
#
#RUN apk del --no-cache .build-deps
#
#RUN mkdir -p /src
#COPY src/ /src/
#RUN pip install -e /src
#COPY tests/ /tests/
#
#WORKDIR /src