"""test

Revision ID: 0c5a21b27a64
Revises: fd55144271ea
Create Date: 2021-03-30 13:46:00.643146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5a21b27a64'
down_revision = 'fd55144271ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_affairs_location', table_name='affairs')
    op.add_column('evenements', sa.Column('location_id', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'evenements', 'locations', ['location_id'], ['uuid'])
    op.add_column('invitations', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('invitations', sa.Column('group_id', sa.String(length=60), nullable=True))
    op.add_column('invitations', sa.Column('phone_number', sa.String(length=100), nullable=True))
    op.add_column('invitations', sa.Column('validated_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'groups', ['group_id'], ['uuid'])
    op.drop_index('idx_locations_polygon', table_name='locations')
    op.add_column('messages', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('messages', 'external_id')
    op.create_index('idx_locations_polygon', 'locations', ['polygon'], unique=False)
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'validated_at')
    op.drop_column('invitations', 'phone_number')
    op.drop_column('invitations', 'group_id')
    op.drop_column('invitations', 'email')
    op.drop_constraint(None, 'evenements', type_='foreignkey')
    op.drop_column('evenements', 'location_id')
    op.create_index('idx_affairs_location', 'affairs', ['location'], unique=False)
    # ### end Alembic commands ###
