"""test

Revision ID: 44bcfd5d2563
Revises: 
Create Date: 2021-03-23 09:51:08.353273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bcfd5d2563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_affairs_location', table_name='affairs')
    op.drop_index('idx_locations_polygon', table_name='locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_locations_polygon', 'locations', ['polygon'], unique=False)
    op.create_index('idx_affairs_location', 'affairs', ['location'], unique=False)
    # ### end Alembic commands ###
