"""add message parent

Revision ID: 7f37af72c71e
Revises: 4f34195b9bda
Create Date: 2021-04-27 07:47:08.713291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f37af72c71e'
down_revision = '4f34195b9bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_id')
    op.create_index('idx_locations_polygon', 'locations', ['polygon'], unique=False)
    op.create_index('idx_affairs_location', 'affairs', ['location'], unique=False)
    # ### end Alembic commands ###
