"""add restricted groups on messages

Revision ID: a878d35f3dcb
Revises: 7f37af72c71e
Create Date: 2021-04-29 16:11:00.898956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a878d35f3dcb'
down_revision = '7f37af72c71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
