# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  referentiels-api:
    build: .
    command: flask run --host=0.0.0.0 --port=5001
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
    networks:
      - default
      - enki_default

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pgdata/dev:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
  enki_default:
    external: true
