build:
	docker-compose -f docker-compose.yml build

build-prod:
	docker-compose -f docker-compose.prod.yml build

up:
	docker-compose -f docker-compose.yml up

upd:
	docker-compose -f docker-compose.yml up -d

upd-prod:
	docker-compose -f docker-compose.prod.yml up -d

down:
	docker-compose -f docker-compose.yml down --remove-orphans

down-prod:
	docker-compose -f docker-compose.prod.yml down --remove-orphans

logs:
	docker-compose -f docker-compose.yml logs

logs-prod:
	docker-compose -f docker-compose.prod.yml logs